server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route #路由的id，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001       #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         #断言，路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**
#            - After=2021-04-02T22:54:53.369+08:00[Asia/Shanghai]  #这个时间之后的请求才好使,下面俩个一样
#            - Before=2021-04-02T22:54:53.369+08:00[Asia/Shanghai]
#            - Between=2021-04-02T22:54:53.369+08:00[Asia/Shanghai],2021-04-02T22:54:53.369+08:00[Asia/Shanghai]
#            - Cookie=username,sml   #俩个参数，第一个是cookie的键username，第二个是value的正则表达式，这里为sml
#            - Header=X-Request-Id,\d+
#            - Method=GET
#            - HOST=**.atguigu.com

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka